all_Funcs = [
    "$If",
    "$ElIf",
    "$authorID",
    "$botID",
    "$botName",
    "$botGuilds",
    "$botAvatar",
    "$botMention",
    "$channelCategoryID",
    "$channelCategoryName",
    "$channelChangedRoles",
    "$channelCreated",
    "$channelDelay",
    "$channelID",
    "$channelMention",
    "$channelName",
    "$channelNsfw",
    "$channelPosition",
    "$channelType",
    "$channelURL",
    "$console",
    "$count",
    "$deletedChannel",
    "$editMessage",
    "$deleteMessage",
    "$get",
    "$getVar",
    "$getUserVar",
    "$guildID",
    "$guildName",
    "$guildTextChannels",
    "$let",
    "$mentions",
    "$messageAuthor",
    "$messageContent",
    "$oldChannel",
    "$onlyIf",
    "$ping",
    "$pyEval",
    "$sendMessage",
    "$sendEmbed",
    "$setServerVar",
    "$setUserVar",
    "$setVar",
    "$slashSend",
    "$sum",
    "$userMention",
    "$userName",
    "$wait",
    '$waitMessage',
    "$waitReaction",
    "$memberJoined",
    "$hasPerm",
    "$message",
    "$charmAI",
    "$purge",
    "$messageID",
    "$userID",
    "$defer"
]

date_funcs = ["$channelCreated"]

ifse = ["$If", "$ElIf"]

no_arg_Funcs = ["$botName",
                "$botID",
                "$authorID",
                "$channelID",
                "$guildID",
                "$ping",
                "$botGuilds",
                "$botAvatar",
                "$botMention",
                "$memberJoined",
                "$messageID",
                "$message",
                "$defer"]

newline_char = "*n*"
