all_Funcs = [
    "$If",
    "$ElIf",
    "$addButton",
    "$addDropdown",
    "$dropdownOption",
    "$interactionReply",
    "$selectedDropdown",
    "$buttonSend",
    "$authorID",
    "$authorName",
    "$botAvatar",
    "$botGuilds",
    "$botID",
    "$botMention",
    "$botName",
    "$channelCategoryID",
    "$channelCategoryName",
    "$channelChangedRoles",
    "$channelCreated",
    "$channelDelay",
    "$channelID",
    "$channelMention",
    "$channelName",
    "$channelNsfw",
    "$channelPosition",
    "$channelType",
    "$channelURL",
    "$charmAI",
    "$console",
    "$contains",
    "$count",
    "$defer",
    "$deleteMessage",
    "$deletedChannel",
    "$divide",
    "$editMessage",
    "$get",
    "$getJson",
    "$getVar",
    "$guildID",
    "$guildName",
    "$guildTextChannels",
    "$hasPerm",
    "$let",
    "$lower",
    "$memberJoined",
    "$mentions",
    "$message",
    "$messageAuthor",
    "$messageContent",
    "$messageID",
    "$newChannel",
    "$multi",
    "$oldChannel",
    "$onlyIf",
    "$ping",
    "$pyEval",
    "$purge",
    "$random",
    "$reactionAdded",
    "$reactionRemoved",
    "$sendMessage",
    "$sendDM",
    "$sendEmbed",
    "$setServerVar",
    "$setUserVar",
    "$setVar",
    "$slashSend",
    "$sub",
    "$sum",
    "$userMention",
    "$userName",
    "$userID",
    "$wait",
    "$waitMessage",
    "$waitReaction"
]

date_funcs = ["$channelCreated"]

ifse = ["$If", "$ElIf"]

no_arg_Funcs = ["$botName",
                "$botID",
                "$authorID",
                "$authorName",
                "$channelID",
                "$guildID",
                "$ping",
                "$botGuilds",
                "$botAvatar",
                "$botMention",
                "$messageID",
                "$message",
                "$defer"]

newline_char = "*n*"